# Static integration guards, not a substitute for live gameplay tests.
file(READ "${SOURCE_ROOT}/src/game/Maps/Map.cpp" map)
file(READ "${SOURCE_ROOT}/src/game/Maps/MapManager.cpp" manager)
file(READ "${SOURCE_ROOT}/src/game/World.cpp" world)
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/PlayerbotScripts.cpp" bots)
file(READ "${SOURCE_ROOT}/src/game/Movement/spline/MoveSplineInit.cpp" spline)
foreach(required "ScriptsProcess();" "i_data->Update(t_diff);" "UpdateScriptedEvents();"
    "eluna->OnMapUpdate(this, t_diff);" "SendObjectUpdates();" "UpdateVisibilityForRelocations();"
    "m_bLoadedGrids[gx][gy]" "IsStaggeredMapWorkDue" "GetMapWorkGeneration()")
    string(FIND "${map}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing map integration: ${required}")
    endif()
endforeach()
foreach(required "sTransportMgr.Update(diff);" "sMapMgr.Update(diff);" "sBattleGroundMgr.Update(diff);"
    "sLFGMgr.Update(diff);" "sLFTMgr.Update(diff);")
    string(FIND "${world}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing world gameplay hook: ${required}")
    endif()
endforeach()
string(FIND "${manager}" "runBatch(work);" firstJoin)
string(FIND "${manager}" "map->CompleteUpdate();" complete)
string(FIND "${manager}" "    SwitchPlayersInstances();" transfer)
if(firstJoin EQUAL -1 OR complete LESS firstJoin OR transfer LESS complete)
    message(FATAL_ERROR "Map owner / completion / transfer ordering changed")
endif()
foreach(forbidden "waitContinentUpdateFinishedUntil" "MarkContinentUpdateFinished")
    string(FIND "${map}${manager}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Worker-to-worker barrier reintroduced")
    endif()
endforeach()
string(REGEX MATCHALL "ai->UpdateAI\\(" aiCalls "${bots}")
list(LENGTH aiCalls aiCallCount)
if(NOT aiCallCount EQUAL 1)
    message(FATAL_ERROR "Expected one module AI dispatch path, found ${aiCallCount}")
endif()
string(FIND "${spline}" "static std::atomic<uint32> splineCounter" atomicSpline)
if(atomicSpline EQUAL -1)
    message(FATAL_ERROR "Worker handoff requires shared movement IDs")
endif()
message(STATUS "PASS: custom script, transport, visibility, AI and phase-order static contracts")
